"use client"
import React from 'react';
import { Providers } from "@/redux/provider";
import Header from '../components/Header.jsx'
// import Footer from '../components/Footer.jsx'
import Footer_common from "../components/Footer_common.jsx"
import './globals.css'
import { ApolloProvider } from '@apollo/client'
import graphQLClient from '../functions/graphql/apolloClient';
import useFirebaseAuth from '../functions/auth/useFirebaseAuth'
import { Bars } from 'react-loader-spinner'
import Center from '../components/utils/Center'
import { UserContext } from '../functions/auth/userContext'

const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  const client = graphQLClient();
  const { user, loading } = useFirebaseAuth()
  React.useEffect(()=>{
    console.log(user)
  }, [user])
  return (
    <html lang="en">
      <body className=" ">
        {loading ?
          <Center>
            <Bars
              width='200'
              color="#4fa94d"
            />
          </Center>
          :
          <UserContext.Provider value={user}>
            <ApolloProvider client={client}>
              <Providers>
                <Header />
                {children}
                <Footer_common />
              </Providers>
            </ApolloProvider>
          </UserContext.Provider>
        }
      </body>
    </html>
  )
}
