"use client"
import React from 'react';
import { Providers } from "@/redux/provider";
import Header from '../components/Header.jsx'
// import Footer from '../components/Footer.jsx'
import Footer_common from "../components/Footer_common.jsx"
import './globals.css'

 const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className=" ">
        <Providers>
          <Header/>
          {children}
          <Footer_common />
        </Providers>
      </body>
    </html>
  )
}
